# Stubs for bayesian_hmm.bayesian_model.variable (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc

class Variable(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def __init__(self) -> None: ...
