import typing
from . import hyperparameter as hyperparameter, states as states, stick_breaking_process as stick_breaking_process, variable as variable
from _typeshed import Incomplete

class AuxiliaryVariable(variable.Variable):
    alpha: Incomplete
    beta: Incomplete
    value: Incomplete
    def __init__(self, alpha: hyperparameter.Hyperparameter, beta: stick_breaking_process.StickBreakingProcess) -> None: ...
    @staticmethod
    def single_variable_log_likelihood(scale: float, value: int, count: int, exact: bool) -> float: ...
    @staticmethod
    def single_variable_resample(scale: float, count: int, exact: bool) -> int: ...
    def log_likelihood(self, counts: typing.Dict[states.State, typing.Dict[states.State, int]], exact: bool = ...) -> float: ...
    def resample(self, counts: typing.Dict[states.State, typing.Dict[states.State, int]], exact: bool = ...) -> typing.Dict[states.State, typing.Dict[states.State, int]]: ...
    def value_aggregated(self) -> typing.Dict[states.State, int]: ...
